# -*- coding: utf-8 -*-
"""day 18.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEMJU9I_LoCjIIVPXnohiJV4yg1OG2J1
"""

#i.png



'''import colorgram



rgb_colors = []

colors = colorgram.extract('i.jpg', 30)
for color in colors:
    r = color.rgb.r
    g = color.rgb.g
    b = color.rgb.b
    new_color = (r, g, b)
    rgb_colors.append(new_color)

print(rgb_colors)'''


#main.py
import turtle as turtle_module
import random

turtle_module.colormode(255)
timmy = turtle_module.Turtle()
timmy.speed("fastest")
timmy.penup()
timmy.hideturtle()
color_list = [(246, 233, 237), (222, 169, 126), (141, 179, 192), (185, 149, 160), (126, 77, 59), (44, 107, 160), (128, 79, 90), (224, 233, 240), (239, 248, 243), (38, 51, 69), (107, 175, 118), (73, 5, 23), (76, 96, 185), (183, 100, 153), (210, 80, 59), (40, 134, 107), (240, 186, 134), (212, 178, 185), (226, 178, 164), (184, 187, 206), (166, 202, 209), (169, 204, 184), (85, 149, 129), (72, 67, 51), (54, 60, 77), (98, 44, 56), (45, 68, 80), (81, 140, 168)]
timmy.setheading(225)
timmy.forward(300)
timmy.setheading(0)
number_of_dots = 100
for dot_count in range(1, number_of_dots + 1):
    timmy.dot(20, random.choice(color_list))
    timmy.forward(50)

    if dot_count % 10 == 0:
        timmy.setheading(90)
        timmy.forward(50)
        timmy.setheading(180)
        timmy.forward(500)
        timmy.setheading(0)



screen = turtle_module.Screen()
screen.exitonclick()