# -*- coding: utf-8 -*-
"""day 10.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u_EnUoPQMH8fErn2_2VB80-71nIQBglK
"""

print('''
           _            _       _
   ___ __ _| | ___ _   _| | __ _| |_ ___  _ __ ___
  / __/ _` | |/ __| | | | |/ _` | __/ _ \| '__/ __|
 | (_| (_| | | (__| |_| | | (_| | || (_) | |  \__
  \___\__,_|_|\___|\__,_|_|\__,_|\__\___/|_|  |___/

 _____________________
|  _________________  |
| | JO           0. | |
| |_________________| |
|  ___ ___ ___   ___  |
| | 7 | 8 | 9 | | + | |
| |___|___|___| |___| |
| | 4 | 5 | 6 | | - | |
| |___|___|___| |___| |
| | 1 | 2 | 3 | | x | |
| |___|___|___| |___| |
| | . | 0 | = | | / | |
| |___|___|___| |___| |
|_____________________|



 ''')

def add(n1, n2):
    return n1 + n2


def subtract(n1, n2):
    return n1 - n2


def multiply(n1, n2):
    return n1 * n2

def divide(n1, n2):
    return n1 / n2

operations = {
    "+": add,
    "-": subtract,
    "*": multiply,
    "/": divide,
}




def calculator():
    should_accumulate = True
    num1 = float(input("what is the first number?: "))

    while should_accumulate:
        for symbol in operations:
            print(symbol)
        operation_symbol = input("pick an operation: ")
        num2 = float(input("what is the next number?: "))
        answer = operations[operation_symbol](num1, num2)
        print(f"{num1} {operation_symbol} {num2} = {answer}")

        choice = input(f"type 'y' to continue calculating with {answer}, or type 'n' ")

        if choice == "y":
            num1 = answer
        else:
            should_accumulate = False
            print("\n" * 20)


calculator()

