# -*- coding: utf-8 -*-
"""day 26.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAlsXqOaZFoJXBcL4r3rOJwhh0SvrUh3
"""

#NATO_PHONETIC_ALPHABET.CSV




letter,code
A,Alfa
B,Bravo
C,Charlie
D,Delta
E,Echo
F,Foxtrot
G,Golf
H,Hotel
I,India
J,Juliet
K,Kilo
L,Lima
M,Mike
N,November
O,Oscar
P,Papa
Q,Quebec
R,Romeo
S,Sierra
T,Tango
U,Uniform
V,Victor
W,Whiskey
X,X-ray
Y,Yankee
Z,Zulu




#MAIN.PY






import pandas
data = pandas.read_csv("nato_phonetic_alphabet.csv")
phonetic_dict = {row.letter: row.code for (index, row) in data.iterrows()}





word = input("Enter a word: ").upper()
output_list = [phonetic_dict[letter] for letter in word]
print(output_list)