# -*- coding: utf-8 -*-
"""day 14.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ckNpqjeXWnrol7Sus-DfNXjP6Gn6rmcN
"""

import random
logo = """
    __  ___       __
   / / / (_)___ _/ /_  ___  _____
  / /_/ / / __ `/ __ \/ _ \/ ___/
 / __  / / /_/ / / / /  __/ /
/_/ ///_/\__, /_/ /_/\___/_/
   / /  /____/_      _____  _____
  / /   / __ \ | /| / / _ \/ ___/
 / /___/ /_/ / |/ |/ /  __/ /
/_____/\____/|__/|__/\___/_/
"""

vs = """
| |  / /____
| | / / ___/
| |/ (__  )
|___/_____)
"""


# -------------------- Data --------------------
data = [
    {'name': 'Cristiano Ronaldo', 'follower_count': 650, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Ariana Grande', 'follower_count': 380, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 395, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Selena Gomez', 'follower_count': 420, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 380, 'description': 'Reality TV star and businesswoman', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 360, 'description': 'Reality TV star and businesswoman', 'country': 'United States'},
    {'name': 'Lionel Messi', 'follower_count': 485, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Beyoncé', 'follower_count': 315, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 290, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Taylor Swift', 'follower_count': 285, 'description': 'Singer-songwriter', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 280, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Kendall Jenner', 'follower_count': 275, 'description': 'Model and TV personality', 'country': 'United States'},
    {'name': 'Jennifer Lopez', 'follower_count': 255, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Nicki Minaj', 'follower_count': 230, 'description': 'Rapper and singer', 'country': 'Trinidad and Tobago'},
    {'name': 'Neymar Jr', 'follower_count': 220, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'Katy Perry', 'follower_count': 190, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower_count': 210, 'description': 'Singer and actress', 'country': 'United States'},
    {'name': 'Rihanna', 'follower_count': 250, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Zendaya', 'follower_count': 185, 'description': 'Actress and singer', 'country': 'United States'},
    {'name': 'Billie Eilish', 'follower_count': 180, 'description': 'Singer and songwriter', 'country': 'United States'},
]






def format_data(account):
    account_name = account["name"]
    account_descr = account["description"]
    account_country = account["country"]
    return f"{account_name}, a {account_descr}, from {account_country}"






def check_answer(user_guess, a_followers, b_followers):
    if a_followers > b_followers:
        return user_guess == "a"
    else:
        return user_guess == "b"
print(logo)



account_a = random.choice(data)
account_b = random.choice(data)


score = 0
game_should_continue = True
account_b = random.choice(data)

while game_should_continue:
    account_a = account_b
    account_b = random.choice(data)

    if account_a == account_b:
        account_b = random.choice(data)

    print(f"Compare A: {format_data(account_a)}.")
    print(vs)
    print(f"Compare B: {format_data(account_b)}.")
    guess = input("Who has more followers? Type 'A' or 'B': ").lower()
    print("\n" * 20)
    print(logo)
    a_follower_count = account_a["follower_count"]
    b_follower_count = account_b["follower_count"]
    is_correct = check_answer(guess, a_follower_count, b_follower_count)
    if is_correct:
        score += 1
        print(f"You're right! Current score {score}")
    else:
        print(f"Sorry, that's wrong. Final score: {score}.")
        game_should_continue = False

