# -*- coding: utf-8 -*-
"""day 1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TYP0_OlfuVvIk3egxHVQKeoxGVfe30IG
"""

print("welcome to the Band Name Generator")
a = input("whats the name of the city you grew up in?\n")
n = input("whats your pet name\n")
print("your band name could be " + a +" " + n )

