# -*- coding: utf-8 -*-
"""day 7.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qfUKy7b95N3nYOKUK-KY6thaU3Og8rjK
"""

import random

print('''
 _
| |
| |__   __ _ _ __   __ _ _ __ ___   __ _ _ __
| '_ \ / _` | '_ \ / _` | '_ ` _ \ / _` | '_ \
| | | | (_| | | | | (_| | | | | | | (_| | | | |
|_| |_|\__,_|_| |_|\__, |_| |_| |_|\__,_|_| |_|
                    __/ |
                   |___/
             ''')














stages = ['''
+---+
 |  |
 O  |
/|\ |
/ \ |
    |
''','''
+---+
|   |
 O  |
/|\ |
/   |
    |
''','''
+---+
 |  |
 O  |
/|\ |
    |
    |
''','''
+---+
 |  |
 O  |
/|  |
    |
    |
''','''
+---+
|   |
O   |
|   |
    |
    |
''','''
+---+
|   |
O   |
    |
    |
    |
''','''
+---+
|   |
    |
    |
    |
    |
''']








list = ["america", "solid", "treasure", "individual"]
lives = 6
chosen_word = random.choice(list)
print(chosen_word)


placeholder = ""
word_length = len(chosen_word)
for position in range(word_length):
    placeholder += "_"
print(placeholder)
game_over = False
correct_letters = []

while not game_over:
    print(f"*******************{lives}/6 LIVES LEFT*****************************")
    guess = input("guess the letter: ").lower()
    if guess in correct_letters:
        print(f"you have already guessed {guess}")

    display = ""

    for letter in chosen_word:
        if letter == guess:
            display += letter
            correct_letters.append(guess)
        elif letter in correct_letters:
            display += letter
        else:
            display += "_"
    print(display)

    if guess not in chosen_word:
        lives -= 1
        print(f"you guessed {guess}, that's not in the word. you loose a life")
        if lives == 0:
            game_over = True
            print(f"***************IT WAS {chosen_word}!You loose*******************")

    if "_" not in display:
        game_over = True
        print("*******************you win*********************")


    print(stages[lives])

