# -*- coding: utf-8 -*-
"""day 12.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kgw9b-qcDemKuzm5avlXYt6W1u0W35PX
"""

from random import randint

logo = '''
  ________                                     __  .__                                      ___.
 /  _____/ __ __   ____   ______ ______      _/  |_|  |__   ____          ____  __ __  _____\_ |__   ___________
/   \  ___|  |  \_/ __ \ /  ___//  ___/      \   __\  |  \_/ __ \        /    \|  |  \/     \| __ \_/ __ \_  __ |
\    \_\  \  |  /\  ___/ \___ \ \___ \        |  | |   Y  \  ___/       |   |  \  |  /  Y Y  \ \_\ \  ___/|  | \/
 \______  /____/  \___  >____  >____  >       |__| |___|  /\___  >      |___|  /____/|__|_|  /___  /\___  >__|
        \/            \/     \/     \/                  \/     \/            \/            \/    \/     \/

'''
EASY_LEVEL_TURNS = 10
HARD_LEVEL_TURNS = 5

def check_answer(user_guess, actual_answer, turns):
    if user_guess > actual_answer:
        print("Too high.")
        return turns - 1
    if user_guess < actual_answer:
        print("Too low.")
        return turns - 1
    else:
        print(f"You get it! The answer was {actual_answer}")

def set_difficulty():
    level = input("Choose a difficulty. Type 'easy' 😎  or 'hard'🔥hard: ")
    if level == "easy":
        return EASY_LEVEL_TURNS
    else:
        return HARD_LEVEL_TURNS

def game():
    print(logo)
    print("Welcome to 🎯🎲 GUESS THE NUMBER 🎲🎯")
    print("🤔💭 I'm thining of a number between 1 to 100.")
    answer = randint(1, 100)
    print(f"Pssst, the correct answer is {answer}")


    turns = set_difficulty()
    guess = 0
    while guess != answer:
        print(f"You have {turns} attempts remaining to guess the number.")
        guess = int(input("Make a guess: "))
        turns = check_answer(guess, answer, turns)
        if turns == 0:
            print("You've run out of guesses, you lose.")
            return
        elif guess != answer:
            print("Guess again.")


game()

